/* CONFIGURAÇÃO DO SCHEMA */
SET SEARCH_PATH TO SCPORTALDADOS;


BEGIN;

/* ============================================================
   SESSÕES DE RENOVAÇÃO DE TOKEN
   ============================================================ */
CREATE TABLE TB_SESSAO_REFRESH (
    CO_SEQ_SESSAO           UUID NOT NULL,
    CO_USUARIO              BIGINT NOT NULL,
    DS_TOKEN_HASH           VARCHAR(64) NOT NULL,
    DT_EXPIRACAO            TIMESTAMPTZ NOT NULL,
    DT_REVOGACAO            TIMESTAMPTZ,
    DT_REGISTRO             TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CO_SESSAO_SUBSTITUTA    UUID,
    DS_IP                   VARCHAR(45),
    DS_USER_AGENT           VARCHAR(500),

    CONSTRAINT PK_TB_SESSAO_REFRESH
        PRIMARY KEY (CO_SEQ_SESSAO),
    CONSTRAINT UQ_TB_SESSAO_REFRESH_TOKEN
        UNIQUE (DS_TOKEN_HASH),
    CONSTRAINT FK_TB_SESSAO_REFRESH_USUARIO
        FOREIGN KEY (CO_USUARIO)
        REFERENCES TB_USUARIO (CO_SEQ_USUARIO)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,
    CONSTRAINT FK_TB_SESSAO_REFRESH_SUBSTITUTA
        FOREIGN KEY (CO_SESSAO_SUBSTITUTA)
        REFERENCES TB_SESSAO_REFRESH (CO_SEQ_SESSAO)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT,
    CONSTRAINT CK_TB_SESSAO_REFRESH_DATAS
        CHECK (DT_EXPIRACAO > DT_REGISTRO)
);

CREATE INDEX IX_TB_SESSAO_REFRESH_USUARIO_ATIVA
    ON TB_SESSAO_REFRESH (CO_USUARIO, DT_EXPIRACAO)
    WHERE DT_REVOGACAO IS NULL;

COMMENT ON TABLE TB_SESSAO_REFRESH IS
    'Mantém hashes dos refresh tokens para rotação e revogação de sessões.';
COMMENT ON COLUMN TB_SESSAO_REFRESH.DS_TOKEN_HASH IS
    'SHA-256 do refresh token. O token original nunca é persistido.';

COMMIT;